### ISSUE TITLE
RuntimeError: cudaErrorIllegalAddress  with Cuda 11.0

### ISSUE THREAD

**Issue by Andy97** [NVIDIA/MinkowskiEngine#283] opened 2020-12-24 08:24 UTC
Running network with pytorch docker "pytorch/pytorch:1.7.0-cuda11.0-cudnn8-devel" triggered error cudaErrorIllegalAddress.
```
Traceback (most recent call last):
  File "Minkowski_backbone.py", line 844, in <module>
    pipeline()
  File "Minkowski_backbone.py", line 835, in pipeline
    losses.backward()
  File "/opt/conda/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorIllegalAddress: an illegal memory access was encountered
Aborted (core dumped)
```

Here is how I initialized the environment
```
sudo apt-get install libopenblas-dev -y && conda install numpy mkl-include pytorch cudatoolkit=11.0 -c pytorch -y
sudo apt-get install git -y && pip install git+https://github.com/NVIDIA/MinkowskiEngine.git@v0.5 --user
python my_program.py
```

While with another docker "pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel" with following initialization code, everything works fine:
```
sudo apt-get install libopenblas-dev -y && conda install numpy mkl-include pytorch cudatoolkit=10.1 -c pytorch -y
sudo apt-get install git -y && pip install git+https://github.com/NVIDIA/MinkowskiEngine.git@v0.5 --user
python my_program.py
```
Since the Cuda 11.0 meets the requirement  11.1 > CUDA >= 10.1.243.
So I'm here to ask "Is there any clue which leads to this error?"
Thanks.

**Comment by chrischoy** [comment] 2020-12-25 03:43
Is there a minimal code that reproduces this error?

**Comment by chrischoy** [comment] 2021-01-08 12:47
Closing the issue since the Minkowski Engine does not use merge sort and likely this error was originated from another library.

**Closed by chrischoy** 2021-01-08 12:47 UTC
